apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:v54BqE2iRC8raLdbn2vdh9c2wep+ENhu1bK7BoKOrJwja7GT,iv:dPxI9HMzol7SSfePpQhvDAF5bgb+DJcKkWarJM4wy+A=,tag:FNhYkkANA2u7uT7ppR9sXQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:UsdFzM5q5y5D,iv:DdUOpHfc9xwAORntGTgy550KdRBFCHf49+MCdXwHOhw=,tag:plTeeLHG++xWCb9Gzk6Rcw==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:GbOXz8k4kApkIp0=,iv:/AqP8ezP5VOwIOReWCUvk7zDOnSKqczJFhY+WmcupR0=,tag:PBVmj8PwEptnpOAg8Q7Mvw==,type:str]
    SECRET_NFS_BACKUP_LH: ENC[AES256_GCM,data:W7sxGDNJ+6FnxVGE84m5O4OmNZr650p9PZKT5xuuGg==,iv:4Um2exJZIPQo+XwFgdbzhEBMBngV4D/+668TQW9MfyM=,tag:0jHxLBsKhCz/Gh7Xv+0IeQ==,type:str]
    SECRET_NFS_MEDIA: ENC[AES256_GCM,data:oE1T6vol2ia3iEfO18xDZOrAHIE=,iv:2HMJoIA3ciuC9rul6+58ETjaod2KHNKMC//8SJOS56I=,tag:lOlP5hZ/5so/2d10z9frng==,type:str]
    SECRET_NFS_MINIO: ENC[AES256_GCM,data:snZdhW79TkVdqPOkgnJQ1xCmGu/u9Na1c5BPVw==,iv:hepfZO1Quvu7UtW5s4AJyxUAP7v+pxNK4PwC31ch1UE=,tag:pAcZGkS2h3OPcpueOiehAA==,type:str]
    SECRET_XEN_IP: ENC[AES256_GCM,data:MJzT4//qaMFQlMI2GQ==,iv:QhHYS78IzLgzHCxEot5ZmranZyYr8IYuE6wV2C8LUdc=,tag:7n8/OL8Kg0NdYqsK4XkK1g==,type:str]
    SECRET_PFSENSE_IP: ENC[AES256_GCM,data:kjHJmaKgqhxt0Qo=,iv:OaRjngNHwVeUWR8sWfVcIdAFO/F97HssuaqDVBs0+fw=,tag:USTwnT3x4CuURl1+OmQ/dA==,type:str]
    SECRET_WINGS_IP: ENC[AES256_GCM,data:RQZ0XdQ6R00Cjq2+sQ==,iv:Pk0pbevnOypy+7J2PFjsPHqwfx1jmyLmzNM2zozzm7Y=,tag:zMuU25unGhhAIsxbcEiOhw==,type:str]
    SECRET_PROJECTS_IP: ENC[AES256_GCM,data:+nWiOkfHrPyAs4NQ,iv:IjtaBmNvmPYUL+RjtqZ4zokMHiUkMKIQd3NOkhaXoZs=,tag:xkdqjIqAQn7k5v0Uv5Nv5g==,type:str]
    SECRET_REDIS_URL: ENC[AES256_GCM,data:x4tEgR6rMbpvPPjjw+eHFOfow5tTwJ0SuqtVcHWlYuC2,iv:MPZ2YEUH/dTuxt9tuQMulcqYETUeIjP5LPHzF9x8ax8=,tag:Oq2ZHt8b8PNG9FH9l4q0ng==,type:str]
    SECRET_MARIADB_URL: ENC[AES256_GCM,data:ZFxYPDs5csbrG6bPWqyg53FR4yVLFnLrXP6oV4scp8GjKHo=,iv:JdI0qbOQWbknRfDhCyMQmqD4zGFm99GeAwUzk8Y0330=,tag:yShs8NmqLS5T1MurwdIYsw==,type:str]
    PTERODACTYL_APP_EMAIL: ENC[AES256_GCM,data:+Jacu2D3iDxxjMYx3XZ/QPr+Jn2lOg==,iv:4z50NR7UU3i4pppyA6hg4/2Bu+Jwyhc3e2E0zSOYk4E=,tag:vJKaWDq+ABMPek5K5FdB+g==,type:str]
    PTERODACTYL_MARIADB_PASSWORD: ENC[AES256_GCM,data:f/L2DKWCnFUBA+FE4wkkAewK60Q=,iv:YIDXSD+OsN+MZYu2QNg3XEvPa7YBZXb/4hfWYgr1wjA=,tag:FNeoc18Z1+cB2PEo0oRwoA==,type:str]
    BOOKSTACK_MARIADB_PASSWORD: ENC[AES256_GCM,data:RI1Z06xWwLko8FXf0hON3Wv5OGI=,iv:0/s2ANN2WAs5gBDuR2Umu9XWiqjYXiQWxTN0g8Q7OHo=,tag:PGW6V4V26wlSoNX3D9tsEw==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:I9wUQOLdqtlYq4w/blH0rmD3BGE=,iv:7pHn4gfRFb7tqWbwYgJnjV4LGDiu1Yld+DdigangcZQ=,tag:0ywQzmXs6AmbHfNPPUq+Ig==,type:str]
    SECRET_APOLLO_IP: ENC[AES256_GCM,data:Xn/NJG9qqenVrAOVjA==,iv:lBU+soL+YS3GquY9n8zqrAx1kBjgjcrGafmwXcYqgyA=,tag:vr6iV0vK4V1bX2LKIyI9bQ==,type:str]
    PI_IP: ENC[AES256_GCM,data:NrZTDd21+4QE08XOgA==,iv:s9XlZOnSAnR2SDfJMHnLiwh5IA6HLnm7Ik7+8XqkeA8=,tag:vSm1jRS5kosh6Tr6A/EsEg==,type:str]
    KUBEAPI_ADDR: ENC[AES256_GCM,data:THsrYmK5xzT6qgd3,iv:ort/6bfHGQjP8xQakLHmCEkzOYfMsrflJCjXkHNNlr4=,tag:nTuJqrf0/igZfZLm+ZXWAQ==,type:str]
    SECRET_UNIFI_IP: ENC[AES256_GCM,data:dENVn8UYUaUytT8=,iv:Nbk164OaoWna+TPZkAuiLl6Uq6hzuAR69ICqnENcc4Q=,tag:3sHU6Pw0iz5GgHeInQgJNQ==,type:str]
    SECRET_AAUTH_IP: ENC[AES256_GCM,data:4iLt/uBjsLmYqzCqbQ==,iv:Wxs9G9ec4cWKqrSPOMtNHfknHuP7q2rnlDYbd3DZmrU=,tag:usLBVZDfRMzFhVdznMn/PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12mrtx0wyqn4p7uqsajkddnyvz50xvrqf4uw8smhxqftsufx379tq4qe5fr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Q3JVRThHcjRtSVg5NVNE
            YzRic29YVHY1YXhtQXdMK0s3VzBvczgzbFNvCnN4V2VtUVJJSWF4VFBERnpTQlNZ
            Ym9QRG9vWlY3bElsU3BGamprMTlvQWsKLS0tIGFtaDA0ckNYUkU4aGRoTVRZZEZp
            RnJSSUM0UHlwdUg2U2JVUVFjMzlHdFkKlzayV6A8GkGQcpPwlxuuh39B8PItrJzr
            8Ic+3CdtqjIxkiBaYKuNjg0GY+fxXjm7vlLQFtC52cHMmqf/PtjgeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-08T07:20:53Z"
    mac: ENC[AES256_GCM,data:Rv6mW+JfUIvxsj1EbT2qDfvcMywXbalJgpkBCSBQxg0nu8v2gomthC7k1B+P6mGSzzie6TpVpeqAvQ2+U+q2FkDE5CFLZroggP5LOzSJbfS5kWT4+EJWX/0Y+0qY0MKGCiWi4xJNDnEP4Ykof6ID6C9SUeTMpJx1LaE2d7O0dYI=,iv:CtlgGCfkXvuwPIiPcTZ8qLfgjT/Tdwf4MdkUWdX0PyI=,tag:qqj1j93KrC0F8u3KVL91ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
