---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smbonn-me
spec:
  commonName: smbonn.me
  dnsNames:
    - smbonn.me
    - "*.smbonn.me"
  duration: 160h # 7 days
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: smbonn-me-tls
