---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./external-apollo.yaml
  - ./external-nas-ui.yaml
  - ./external-xen-ui.yaml
  # - ./external-pfsense-ui.yaml
  # - ./external-wings.yaml
  # - ./external-projects.yaml
  # - ./external-unifi.yaml
